version: "2.0"
services:
# MySQL适合从节点容器化，增加节点的实例数，从而增加吞吐量;
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/logs/:/logs/
      - ./conf:/etc/mysql/conf.d
      - './sql:/docker-entrypoint-initdb.d' # 初始化sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mytest   #创建mytest用户
      - MYSQL_PASSWORD=mytest  #设置mytest用户的密码
      - TZ=Asia/Shanghai
    restart: always
