version: '4'
services: 
  nginx: 
   # image: nginx:1.18.0
    image: nginx:local
    build:
      context: .
      dockerfile: Dockerfile
    restart: always #重启docker后该容器也重启
    container_name: nginx #容器名
    network_mode: host
    ports:
      - 80:80 #本地端口号与容器内部端口号
      - 443:443 #本地端口号与容器内部端口号  
    volumes: #指定挂载目录
      - /data/nginx/html:/usr/share/nginx/html:ro
      - /data/nginx/log:/var/log/nginx:rw
      - ./conf:/etc/nginx/current/
      - /data/nginx/conf:/etc/nginx/target/
      ##    environment:
      ##    - NGINX_HOST=tyd.com
      ##      - NGINX_PORT=80
    
