version: '2.2'
services:
  minio:
    image: "quay.io/minio/minio:RELEASE.2022-08-02T23-59-16Z"
    container_name: minio
    privileged: true
    restart: always
    ports:
      - "9006:9006"
      - "9007:9007"
    volumes:
      - ./aa/data/:/data/
    command: server --address ":9006" --console-address ":9007" /data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=IjudisjIUJId498eNINxx
    network_mode: host