FROM nginx:1.18.0

ARG webDir
ARG webName

# 将 Nginx 配置文件模板拷到容器中
COPY ${webDir}/nginx.conf /etc/nginx/conf.d/
# COPY default.conf.ssl.template /etc/nginx/conf.d/default.conf.ssl.template
# 将静态资源 拷到容器
ADD ${webDir}/dist /usr/share/nginx/html/

# 初始化脚本, 根据环境变量和模板生成 Nginx 配置文件
#COPY ./run.sh /docker-entrypoint.sh
#RUN chmod a+x /docker-entrypoint.sh
#ENTRYPOINT ["/docker-entrypoint.sh"]

# 每次容器启动时执行
CMD [ "nginx", "-g", "daemon off;" ]

#EXPOSE 80
#EXPOSE 443

