version : '3.8'

services:  
  ryu-pay-web:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        webName: ryu-pay-web
        webDir: ./
    ports:
      - "80:80"
    network_mode: host
