version : '3.8'

services:
  admin:
    image: admin  # 构建镜像名
    container_name: admin   # 容器名称
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        jarName: admin-1.0.0-SNAPSHOT
        jarDir: services/admin
    ports:
      - "30001:30001"
    restart: always
    network_mode: host  #网络，使通信宿主机
    env_file: ./.env  # 环境文件
    volumes:
      - ./services/admin/application.yml:/app/jar/application.yml # 挂载外部配置文件到容器的 /app 目录
      - ./services/admin/bootstrap.yml:/app/jar/bootstrap.yml
      - ${LOG_DIR:-/data/service-data}/admin/logs:/root/.admin/logs    #将日志目录与外部的挂载
    environment:
      - TZ=Asia/Shanghai
    command:
    #  - -Xms1024m
    #  - -Xmx1024m
      - --spring.config.location=/app/jar/application.yml,/app/jar/bootstrap.yml   #commond会附加到entryponint当中

