version: "3"
services:

  redis:
    image: redis:5.0.4
    privileged: true  # 授权
    ports:
      - 25001:6379
    container_name: redis
    restart: always
    volumes:
      - /data/redis/data:/data
      - ./redis.conf:/etc/redis/redis.conf # 把当前的redis.conf挂载到容器中
    command: redis-server /etc/redis/redis.conf --requirepass 'root'
