services:
  skywalking-oap:
    image: apache/skywalking-oap-server:9.2.0
    container_name: skywalking-oap
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "12800:12800"
      - "11800:11800"
    restart: always

  skywalking-ui:
    image: apache/skywalking-ui:9.2.0
    container_name: skywalking-ui
    environment:
      - TZ=Asia/Shanghai
      - SW_OAP_ADDRESS=http://skywalking-oap:12800
    ports:
      - "8088:8080"
    restart: always
    depends_on:
      - skywalking-oap
